spring.application.name=Hospital_management

spring.datasource.url=jdbc:postgresql://localhost:5432/Hospital_management
spring.datasource.username=postgres
spring.datasource.password=Suvam@321
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql